# config/deploy.yml
service: recipe_book
image: vicentetroncosoc/recipe_book

servers:
  web:
    - 178.128.75.254

registry:
  username: vicentetroncosoc
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    RAILS_ENV: "production"
    RAILS_LOG_TO_STDOUT: "1"
    RAILS_SERVE_STATIC_FILES: "1"
    SOLID_QUEUE_IN_PUMA: "true"
  file:
    - .kamal/apps/recipe_book/env/roles/web.env

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

accessories:
  db:
    image: postgres:16
    # expone el puerto para que puedas probar desde fuera si quieres (psql)
    ports:
      - "5432:5432"
    env:
      clear:
        POSTGRES_USER: recipe
        POSTGRES_DB: recipe_production
      secret:
        - POSTGRES_PASSWORD
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    labels:
      service: "recipe_book-db"

volumes:
  - "recipe_book_storage:/rails/storage"

builder:
  arch: amd64