# config/deploy.yml
service: recipe_book
image: vicentetroncosoc/recipe_book

servers:
  web:
    hosts:
      - 178.128.75.254   # ‚Üê tu droplet

registry:
  username: vicentetroncosoc
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    RAILS_ENV: "production"
    RAILS_LOG_TO_STDOUT: "1"
    RAILS_SERVE_STATIC_FILES: "1"
    SOLID_QUEUE_IN_PUMA: "true"
  # üëá Cargamos variables desde el archivo que YA creaste
  file:
    - .kamal/apps/recipe_book/env/roles/web.env
  # ‚ùå Nada en secret aqu√≠ para DB o SECRET_KEY_BASE.
  #    SECRET_KEY_BASE viene de credentials via RAILS_MASTER_KEY (en web.env).

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

accessories:
  db:
    image: postgres:16
    host: 178.128.75.254
    roles: [web]
    port: "5432:5432"
    env:
      clear:
        POSTGRES_USER: recipe
        POSTGRES_DB: recipe_production
      secret:
        - POSTGRES_PASSWORD
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    labels:
      service: "recipe_book-db"

volumes:
  - "recipe_book_storage:/rails/storage"

healthcheck:
  path: /up
  interval: 3s
  timeout: 2s
  retries: 10

builder:
  arch: amd64